import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import jsPDF from "jspdf";

import DashboardLayout from "../../components/dashboard/DashboardLayout";
import { useAuth } from "../../contexts/AuthContext";
import { getMyTenancy } from "../../firebase/tenancyService";

function Contract() {
  const { user } = useAuth();
  const navigate = useNavigate();

  const [tenancy, setTenancy] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadTenancy() {
      if (!user?.uid) return;

      try {
        const data = await getMyTenancy(user.uid);

        setTenancy(data);
      } catch (error) {
        console.error(
          "Error loading tenancy:",
          error,
        );
      } finally {
        setLoading(false);
      }
    }

    loadTenancy();
  }, [user]);

  // ==========================================
  // DOWNLOAD PDF
  // ==========================================

  function downloadContract() {
    if (!tenancy) return;

    const pdf = new jsPDF();

    let y = 20;

    // Header
    pdf.setFontSize(22);
    pdf.setFont("helvetica", "bold");

    pdf.text("RentEase", 105, y, {
      align: "center",
    });

    y += 10;

    pdf.setFontSize(16);

    pdf.text("RESIDENTIAL RENTAL AGREEMENT", 105, y, {
      align: "center",
    });

    y += 18;

    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");

    // Helper
    function addField(label, value) {
      pdf.setFont("helvetica", "bold");
      pdf.text(`${label}:`, 20, y);

      pdf.setFont("helvetica", "normal");

      pdf.text(String(value || "N/A"), 65, y);

      y += 9;
    }

    // Landlord
    pdf.setFontSize(13);
    pdf.setFont("helvetica", "bold");

    pdf.text("LANDLORD INFORMATION", 20, y);

    y += 10;

    pdf.setFontSize(11);

    addField(
      "Name",
      tenancy.landlordName,
    );

    addField(
      "Email",
      tenancy.landlordEmail,
    );

    y += 5;

    // Tenant
    pdf.setFontSize(13);
    pdf.setFont("helvetica", "bold");

    pdf.text("TENANT INFORMATION", 20, y);

    y += 10;

    pdf.setFontSize(11);

    addField(
      "Name",
      tenancy.tenantName,
    );

    addField(
      "Email",
      tenancy.tenantEmail,
    );

    addField(
      "Phone",
      tenancy.tenantPhone,
    );

    y += 5;

    // Property
    pdf.setFontSize(13);
    pdf.setFont("helvetica", "bold");

    pdf.text("PROPERTY INFORMATION", 20, y);

    y += 10;

    pdf.setFontSize(11);

    addField(
      "Property",
      tenancy.propertyTitle,
    );

    addField(
      "Address",
      tenancy.propertyAddress,
    );

    addField(
      "City",
      tenancy.propertyCity,
    );

    addField(
      "State",
      tenancy.propertyState,
    );

    y += 5;

    // Rental details
    pdf.setFontSize(13);
    pdf.setFont("helvetica", "bold");

    pdf.text("RENTAL DETAILS", 20, y);

    y += 10;

    pdf.setFontSize(11);

    addField(
      "Rent",
      `NGN ${Number(
        tenancy.rentAmount || 0,
      ).toLocaleString()}`,
    );

    addField(
      "Start Date",
      tenancy.contractStartDate ||
        tenancy.moveInDate,
    );

    addField(
      "End Date",
      tenancy.contractEndDate ||
        "Not specified",
    );

    addField(
      "Status",
      tenancy.status,
    );

    y += 10;

    // Agreement text
    pdf.setFontSize(13);
    pdf.setFont("helvetica", "bold");

    pdf.text(
      "AGREEMENT",
      20,
      y,
    );

    y += 9;

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");

    const agreementText =
      "This document records the rental relationship between the landlord and tenant through the RentEase rental management system. The tenant agrees to occupy the property subject to the agreed rental terms and the applicable rental conditions.";

    const lines = pdf.splitTextToSize(
      agreementText,
      170,
    );

    pdf.text(lines, 20, y);

    y += lines.length * 6 + 15;

    // Signatures
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "bold");

    pdf.text(
      "Landlord Signature: ____________________",
      20,
      y,
    );

    pdf.text(
      "Tenant Signature: ____________________",
      20,
      y + 15,
    );

    y += 30;

    pdf.setFont("helvetica", "normal");

    pdf.setFontSize(9);

    pdf.text(
      "Generated by RentEase Rental Management System",
      105,
      285,
      {
        align: "center",
      },
    );

    pdf.save(
      `RentEase-Contract-${tenancy.propertyTitle || "Rental"}.pdf`,
    );
  }

  // ==========================================
  // LOADING
  // ==========================================

  if (loading) {
    return (
      <DashboardLayout>
        <div className="flex min-h-[50vh] items-center justify-center">
          <p className="text-slate-500">
            Loading contract...
          </p>
        </div>
      </DashboardLayout>
    );
  }

  // ==========================================
  // NO TENANCY
  // ==========================================

  if (!tenancy) {
    return (
      <DashboardLayout>
        <div className="mx-auto max-w-3xl rounded-2xl bg-white p-10 text-center shadow-sm">

          <h1 className="text-2xl font-bold text-slate-800">
            No Rental Contract
          </h1>

          <p className="mt-3 text-slate-500">
            You do not currently have an active rental
            contract.
          </p>

          <button
            onClick={() =>
              navigate("/tenant/my-rental")
            }
            className="mt-6 rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white hover:bg-blue-700"
          >
            Back to My Rental
          </button>

        </div>
      </DashboardLayout>
    );
  }

  // ==========================================
  // CONTRACT PAGE
  // ==========================================

  return (
    <DashboardLayout>
      <div className="mx-auto max-w-4xl">

        {/* Header */}
        <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-center">

          <div>
            <h1 className="text-3xl font-bold text-slate-800">
              Rental Contract
            </h1>

            <p className="mt-2 text-slate-500">
              Your rental agreement with the property
              owner.
            </p>
          </div>

          <button
            onClick={downloadContract}
            className="rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white hover:bg-blue-700"
          >
            Download PDF
          </button>

        </div>

        {/* Contract */}
        <div className="rounded-2xl bg-white p-8 shadow-sm md:p-12">

          {/* Logo */}
          <div className="text-center">

            <h2 className="text-3xl font-bold text-blue-600">
              RentEase
            </h2>

            <p className="mt-2 font-semibold text-slate-700">
              RESIDENTIAL RENTAL AGREEMENT
            </p>

          </div>

          <div className="my-8 border-t" />

          {/* Landlord */}
          <section className="mb-8">

            <h3 className="mb-4 text-lg font-bold text-slate-800">
              Landlord Information
            </h3>

            <div className="grid gap-4 sm:grid-cols-2">

              <Info
                label="Name"
                value={tenancy.landlordName}
              />

              <Info
                label="Email"
                value={tenancy.landlordEmail}
              />

            </div>

          </section>

          {/* Tenant */}
          <section className="mb-8">

            <h3 className="mb-4 text-lg font-bold text-slate-800">
              Tenant Information
            </h3>

            <div className="grid gap-4 sm:grid-cols-2">

              <Info
                label="Name"
                value={tenancy.tenantName}
              />

              <Info
                label="Email"
                value={tenancy.tenantEmail}
              />

              <Info
                label="Phone"
                value={tenancy.tenantPhone}
              />

            </div>

          </section>

          {/* Property */}
          <section className="mb-8">

            <h3 className="mb-4 text-lg font-bold text-slate-800">
              Property Information
            </h3>

            <div className="grid gap-4 sm:grid-cols-2">

              <Info
                label="Property"
                value={tenancy.propertyTitle}
              />

              <Info
                label="Address"
                value={tenancy.propertyAddress}
              />

              <Info
                label="City"
                value={tenancy.propertyCity}
              />

              <Info
                label="State"
                value={tenancy.propertyState}
              />

            </div>

          </section>

          {/* Rental Details */}
          <section className="mb-8">

            <h3 className="mb-4 text-lg font-bold text-slate-800">
              Rental Details
            </h3>

            <div className="grid gap-4 sm:grid-cols-2">

              <Info
                label="Rent"
                value={`₦${Number(
                  tenancy.rentAmount || 0,
                ).toLocaleString()}`}
              />

              <Info
                label="Start Date"
                value={
                  tenancy.contractStartDate ||
                  tenancy.moveInDate
                }
              />

              <Info
                label="End Date"
                value={
                  tenancy.contractEndDate ||
                  "Not specified"
                }
              />

              <Info
                label="Status"
                value={tenancy.status}
              />

            </div>

          </section>

          {/* Agreement */}
          <section>

            <h3 className="mb-4 text-lg font-bold text-slate-800">
              Agreement
            </h3>

            <p className="leading-7 text-slate-600">
              This document records the rental relationship
              between the landlord and tenant through the
              RentEase rental management system. The tenant
              agrees to occupy the property subject to the
              agreed rental terms and applicable rental
              conditions.
            </p>

          </section>

          {/* Signatures */}
          <div className="mt-12 grid gap-10 sm:grid-cols-2">

            <div>
              <div className="mb-2 border-b border-slate-400" />

              <p className="text-sm text-slate-500">
                Landlord Signature
              </p>
            </div>

            <div>
              <div className="mb-2 border-b border-slate-400" />

              <p className="text-sm text-slate-500">
                Tenant Signature
              </p>
            </div>

          </div>

          <div className="mt-12 text-center text-xs text-slate-400">
            Generated by RentEase Rental Management System
          </div>

        </div>
      </div>
    </DashboardLayout>
  );
}

// ==========================================
// INFO COMPONENT
// ==========================================

function Info({ label, value }) {
  return (
    <div className="rounded-lg bg-slate-50 p-4">
      <p className="text-sm text-slate-500">
        {label}
      </p>

      <p className="mt-1 font-semibold text-slate-800">
        {value || "N/A"}
      </p>
    </div>
  );
}

export default Contract;